theme = "semi-native"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
hide_inactive = true
hide_missing = true

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 10
format = "%a %m/%d %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
